apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role
  # namespace ommitted since cluster roles are not namespaced 
rules:
- apiGroups: ""
  resources: ["Deployment"]
  verbs: ["get","list","watch"]
  
  