apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql 
data:
  primary.cnf: |
   # apply this configuration to primary db
    [mysqld]
    log-bin
  replica.cnf: |
   # apply this configuration to replicas
    [mysqld]
    super-read-only