apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: statefulset-mysql
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  template:
    metadata:
      labels: 
        app: mysql
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values: node-1
              topologyKey: kubernetes.io/host
      containers:
      - name: mysql
        image: mysql:latest
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
          - name: mysql-vol
            mountPath: /var/lib/mysql
        env:
          valueFrom:
            secretKeyRef:
              - name: secret-mysql
                key: MYSQL_ROOT_PASSWORD
volumeClaimTemplates:
- metadata:
    name: mysql-vol
  spec:
    accessModes: ["ReadWriteOnce"]
    storageClassName: my-storage-class
    resources:
      requests:
        storage: "1Gi"